zopsedu/common/kullanici_profil/models.py
"""Ozgecmis modeli"""
from sqlalchemy import Column, Integer, ForeignKey, Text
from sqlalchemy.orm import relationship

from zopsedu.lib.db import BASE_MODEL, ZopseduBase


class Ozgecmis(BASE_MODEL, ZopseduBase):
    """Ozgecmis Modeli
    """
    __tablename__ = "ozgecmis"

    id = Column(Integer, primary_key=True)
    tecrube = Column(Text)
    file_id = Column(Integer, ForeignKey("file.id"))
    user_id = Column(Integer, ForeignKey("users.id"))
    user = relationship("User", uselist=False)
    file = relationship("File")

zopsedu/common/kullanici_profil/forms.py
"""Kullanici Profil"""

from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, FileField, PasswordField, validators, StringField, \
    TextAreaField, \
    IntegerField
from flask_babel import gettext as _
from wtforms.validators import DataRequired, Email, Length

from zopsedu.auth.models.auth import RolTipleri

from zopsedu.lib.form.fields import SummerNoteField, Select2Field, HiddenIntegerField
from zopsedu.lib.form.validators import FileExtensionRestriction
from zopsedu.models.helpers import BirimTipiEnum

ROLLER = [(r.name, r.value) for r in RolTipleri]


class AvatarGuncelleForm(FlaskForm):
    """Kullanici Avatar Guncelleme Formu"""

    avatar = FileField(label=_('Avatar'))
    guncelle = SubmitField(label=_('Güncelle'))


class RolForm(FlaskForm):
    """Rol Degistirme Formu"""

    roles = SelectField(label='Rol', render_kw={'class': 'form-control'}, coerce=int)
    degistir = SubmitField(label=_('Rolü Değiştir'))


class PasswordChangeForm(FlaskForm):
    """Login Form"""

    old_password = PasswordField(
        validators=[
            validators.DataRequired(message=_('Bu alan boş bırakılamaz.')),
            validators.Length(3, 16, message=_('Parola en az 3, en fazla 16 karakterden oluşmalı.'))
        ],
        render_kw={"placeholder": _("Eski Parola")})
    new_password = PasswordField(
        validators=[
            validators.DataRequired(message=_('Bu alan boş bırakılamaz.')),
            validators.Length(3, 16,
                              message=_('Parola en az 3, en fazla 16 karakterden oluşmalı.')),
            validators.EqualTo('re_password', message=_('Girdiğiniz parolalar eşleşmelidir.'))
        ],
        render_kw={"placeholder": _("Yeni Parola")})
    re_password = PasswordField(
        validators=[
            validators.DataRequired(message=_('Bu alan boş bırakılamaz.')),
            validators.Length(3, 16,
                              message=_('Parola en az 3, en fazla 16 karakterden oluşmalı.')),
            validators.EqualTo('new_password', message=_('Girdiğiniz parolalar eşleşmelidir.'))
        ],
        render_kw={"placeholder": _("Yeni Parola Onayla")})

    confirm = PasswordField('Repeat Password')
    degistir = SubmitField(label=_('Değiştir'))


class HariciOgretimElemaniFormu(FlaskForm):
    tckn = IntegerField(label=_("TC Kimlik No : "),
                        validators=[validators.DataRequired(message=_('Bu alan boş bırakılamaz.'))])
    unvan = StringField(label=_("Unvan : "), validators=[Length(max=50)])
    ad = StringField(label=_("Ad : "),
                     validators=[validators.DataRequired(message=_('Bu alan boş bırakılamaz.')), Length(max=50)])
    soyad = StringField(label=_("Soyad : "),
                        validators=[validators.DataRequired(message=_('Bu alan boş bırakılamaz.')), Length(max=50)])
    birincil_eposta = StringField(label=_("Eposta : "),
                                  validators=[validators.DataRequired(
                                      message=_('Bu alan boş bırakılamaz.')), Length(max=50),
                                              Email(message='Bir email adresi girmelisiniz')])

    ikincil_eposta = StringField(label=_("İkinci Eposta : "),
                                 validators=[
                                     validators.DataRequired(message=_('Bu alan boş bırakılamaz.')), Length(max=50),
                                     Email(message='Bir email adresi girmelisiniz')])
    ev_tel_no = IntegerField(label=_("Ev Telefonu : "))
    cep_tel = IntegerField(label=_("Cep Tel. : "))
    adres = TextAreaField(label=_("Adres :"))
    adres2 = TextAreaField(label=_("Adres2 :"))
    akademik_yayinlari = TextAreaField(label=_('Akademik Yayınları :'))
    banka_adi = StringField(label=_('Banka Adı : '), validators=[Length(max=100)])
    sube_adi = StringField(label=_('Şube Adı : '), validators=[Length(max=100)] )
    sube_kod = IntegerField(label=_('Şube Kodu : '))
    hesap_no = IntegerField(label=_('Hesap No : '))
    iban_no = StringField(label=_('Iban No : '), validators=[Length(max=100)])
    submit = SubmitField(label=_('Kaydet'))

    universite = Select2Field(_('Üniversite Seç'),
                              url="/select/birim",
                              validators=[
                                  DataRequired(message=_("Üniversite alanı boş bırakılamaz"))
                              ],
                              placeholder=_("Üniversite"),
                              node_name="fakulte_parent",
                              birim_tipi=BirimTipiEnum.universite.value,
                              kurum_ici=True)

    fakulte = Select2Field(_('Fakülte Seç'), url="/select/birim",
                           validators=[DataRequired(message=_("Bölüm alanı boş bırakılamaz"))],
                           placeholder=_("Fakülte"),
                           dependent="fakulte_parent",
                           node_name="bolum_parent",
                           birim_tipi=BirimTipiEnum.fakulte.value,
                           kurum_ici=True)

    bolum = Select2Field(_('Bölüm Seç'),
                         url="/select/birim",
                         validators=[
                             DataRequired(
                                 message=_("Bölüm alanı boş bırakılamaz"))
                         ],
                         placeholder=_("Bölüm"),
                         dependent="bolum_parent",
                         birim_tipi=BirimTipiEnum.bolum.value,
                         kurum_ici=True)

    unvan = Select2Field(label=_('Ünvan'),
                         validators=[
                             DataRequired(
                                 message=_("Ünvan boş bırakılamaz"))
                         ],
                         url='/select/hitap_unvan')


class OzgecmisKayitFormu(FlaskForm):
    """Ozgecmis kayit Formu
       Kullanici dosya ile ozgecmis yukler,
         aksi takdirde gerekli alanlari doldurur.
    """
    ad = StringField(label=_("Ad: "), validators=[Length(max=50)])
    soyad = StringField(label=_("Soyad: "), validators=[Length(max=50)])
    dogum_tarihi = StringField(label=_("Doğum Tarihi: "))
    tecrube = SummerNoteField(label=_("Tecrübe: "))
    ozgecmis_dosya = FileField(
        label=_("Dosya seçerseniz varolan özgeçmiş dosyanız güncellenecektir!"),
        validators=[FileExtensionRestriction(error_message=_("Lütfen uzantısı geçerli bir dosya yükleyiniz."))])
    ozgecmis_dosya_id = HiddenIntegerField(_("Dosya"))
    kaydet = SubmitField(label=_("Kaydet"))

zopsedu/common/kullanici_profil/blueprint.py
"""KULLANICI PROFIL MODULÜ"""
from flask import Blueprint
from zopsedu.common.kullanici_profil.views import KullaniciProfilView

# pylint: disable=invalid-name
kullanici_profil_bp = Blueprint(
    "kullanici_profil",
    __name__,
    template_folder='templates/'
)
KullaniciProfilView.register(kullanici_profil_bp, route_base="/profil")

# pylint: enable=invalid-name

zopsedu/common/kullanici_profil/views.py
"""Kullanici Profil"""
from _sha512 import sha512

from flask import render_template, request, redirect, url_for, flash, jsonify, current_app, send_file, abort
from flask import session
from flask_babel import gettext as _
from flask_classful import FlaskView, route
from flask_login import login_required, current_user
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import joinedload

from zopsedu.app import DB
from zopsedu.auth.models.auth import User
from zopsedu.auth.lib import auth
from zopsedu.auth.models.auth import UserRole
from zopsedu.bap.lib.auth import OzgecmisKaydetme
from zopsedu.common.kullanici_profil.models import Ozgecmis
from zopsedu.common.mesaj.models import Mesaj
from zopsedu.lib.error_logger import CustomErrorHandler
from zopsedu.lib.signals.signal_sender import signal_sender
from zopsedu.models import File, Person
from zopsedu.personel.models.harici_ogretim_elemani import HariciOgretimElemani
from zopsedu.personel.models.personel import Personel
from .forms import AvatarGuncelleForm, RolForm, OzgecmisKayitFormu, PasswordChangeForm, HariciOgretimElemaniFormu
from zopsedu.lib.user_activity_messages import USER_ACTIVITY_MESSAGES


class KullaniciProfilView(FlaskView):
    """KullaniciProfilView"""

    @property
    def user_id(self):
        """Current User's id"""
        return current_user.get_id()

    @property
    def qry(self):
        """User objesi dondurur."""
        return User.query.filter(User.id == self.user_id).options(joinedload(User.person))

    @property
    def avatar(self):  # pylint: disable=inconsistent-return-statement
        """User avatar dondurur."""
        user = DB.session.query(User.avatar.label("avatar")).filter(User.id == self.user_id).first()
        if user.avatar:
            return current_app.wsgi_app.url_for(user.avatar.path)

    @property
    def _ozgecmis(self):
        return DB.session.query(
            Ozgecmis
        ).filter(
            Ozgecmis.user_id == self.user_id
        )

    @login_required
    @route('/', methods=["GET"], endpoint='profil_goruntule')
    def profil_goruntule(self):
        """Profil Goruntile"""
        args = request.args.get('args')
        user = self.qry.one()

        personel = DB.session.query(Personel).filter(Personel.person_id == user.person.id). \
            options(
            joinedload(Personel.person).joinedload(Person.odeme_bilgileri)
        ).first()

        # todo: bap memurunu role göre filtereliyor personel tablosuna ilgili birim eklendiğinde değişecek.
        if session['current_user_role'] == 2 or session['current_user_role'] == 5:
            return render_template('profil.html',
                               user=user,
                               bap_memuru=personel,
                               avatar_url=self.avatar)


        elif personel:
            return render_template('profil.html',
                                   user=user,
                                   personel=personel,
                                   avatar_url=self.avatar
                                   )


        else:

            harici_ogretim_elemani = DB.session.query(HariciOgretimElemani). \
                filter(HariciOgretimElemani.person_id == user.person.id). \
                options(joinedload(HariciOgretimElemani.person).joinedload(Person.odeme_bilgileri)
                        ).first()

            form = HariciOgretimElemaniFormu(
                tckn=harici_ogretim_elemani.person.tckn,
                unvan=harici_ogretim_elemani.unvan,

                ad=harici_ogretim_elemani.person.ad,
                soyad=harici_ogretim_elemani.person.soyad,
                birincil_eposta=harici_ogretim_elemani.person.birincil_eposta,
                ikincil_eposta=harici_ogretim_elemani.person.ikincil_eposta,
                ev_tel_no=harici_ogretim_elemani.person.ev_tel_no,
                cep_tel=harici_ogretim_elemani.person.cep_telefonu,
                adres=harici_ogretim_elemani.person.ikametgah_adresi.adres,
                adres2=harici_ogretim_elemani.person.ikincil_adres.adres,
                akademik_yayinlari = harici_ogretim_elemani.yayinlar,
                banka_adi=harici_ogretim_elemani.person.odeme_bilgileri[0].banka_adi,
                sube_adi=harici_ogretim_elemani.person.odeme_bilgileri[0].sube_adi,
                sube_kod=harici_ogretim_elemani.person.odeme_bilgileri[0].sube_kod,
                hesap_no=harici_ogretim_elemani.person.odeme_bilgileri[0].hesap_no,
                iban_no=harici_ogretim_elemani.person.odeme_bilgileri[0].iban_no,
                )
            return render_template('profil.html',
                                   user=user,
                                   harici_ogretim_elemani=harici_ogretim_elemani,
                                   form=form,
                                   args=args,
                                   avatar_url=self.avatar
                                   )


    @login_required
    @route('/', methods=["POST"], endpoint='profil_kaydet')
    def profil_kaydet(self):
        """Profil kaydet"""
        user = self.qry.one()
        harici_ogretim_elemani = DB.session.query(HariciOgretimElemani). \
            filter(HariciOgretimElemani.person_id == user.person.id). \
            options(joinedload(HariciOgretimElemani.person).joinedload(Person.odeme_bilgileri)
                    ).first()

        form = HariciOgretimElemaniFormu(request.form)
        if form.validate():
            try:
                harici_ogretim_elemani.person.tckn = request.form['tckn']
                harici_ogretim_elemani.unvan = request.form['unvan']
                harici_ogretim_elemani.person.ad = request.form['ad']
                harici_ogretim_elemani.person.soyad = request.form['soyad']
                harici_ogretim_elemani.person.birincil_eposta = request.form['birincil_eposta']
                harici_ogretim_elemani.person.ikincil_eposta = request.form['ikincil_eposta']
                harici_ogretim_elemani.person.ev_tel_no = request.form['ev_tel_no']
                harici_ogretim_elemani.person.cep_telefonu = request.form['cep_tel']
                harici_ogretim_elemani.person.ikametgah_adresi.adres = request.form['adres']
                harici_ogretim_elemani.person.ikincil_adres.adres = request.form['adres2']
                harici_ogretim_elemani.yayinlar = request.form['akademik_yayinlari']
                harici_ogretim_elemani.person.odeme_bilgileri[0].banka_adi = request.form['banka_adi']
                harici_ogretim_elemani.person.odeme_bilgileri[0].sube_adi = request.form['sube_adi']
                harici_ogretim_elemani.person.odeme_bilgileri[0].sube_kod = request.form['sube_kod']
                harici_ogretim_elemani.person.odeme_bilgileri[0].hesap_no = request.form['hesap_no']
                harici_ogretim_elemani.person.odeme_bilgileri[0].iban_no = request.form['iban_no']
                DB.session.commit()
            except SQLAlchemyError as error:
                DB.session.rollback()
                CustomErrorHandler.error_handler(
                    hata="Harici hakem eklenmeye ""çalışıldı. Hata: {}".format(error))
                return abort(500)
            signal_payload = {
                "message_type": USER_ACTIVITY_MESSAGES.get("common").get("harici_profil_guncelle").type_index,
                "nesne": 'Harici ogretim elemani',
                "nesne_id": harici_ogretim_elemani.id,
                "ekstra_mesaj": "{} adlı {} idli harici ogretim elemani "
                                "profil bilgilerini değiştirdi"
                                ".".format(current_user.username, current_user.id)
            }
            signal_sender(**signal_payload)
            success_msg = _('Profil bilgilerinizi başarıyla değiştirdiniz.')
            args = {
                'success_msg': success_msg,
            }
            return render_template('profil.html',
                                   user=user,
                                   harici_ogretim_elemani=harici_ogretim_elemani,
                                   form=form,
                                   args=args)
        else:
            args = {'unknown_error': 'Profil bilgilerinizi değiştirirken bir hata oluştu.'}
            return render_template('profil.html',
                                   user=user,
                                   harici_ogretim_elemani=harici_ogretim_elemani,
                                   form=form,
                                   args=args)


    @login_required
    @route('/avatar', methods=["GET"], endpoint='avatar')
    def avatar_guncelle(self):
        """Avatar guncelle get"""
        user = self.qry.one()
        avatar_form = AvatarGuncelleForm(request.form)

        return render_template('avatar_guncelle.html', avatar_form=avatar_form,
                               user=user,
                               avatar_url=self.avatar)

    @login_required
    @route('/avatar', methods=["POST"])
    def post_avatar_guncelle(self):
        """Avatar guncelle post"""
        user = self.qry.one()
        avatar = request.files.get('avatar', None)

        try:
            if avatar:
                user.avatar = avatar
                DB.session.commit()
                signal_payload = {
                    "message_type": USER_ACTIVITY_MESSAGES.get("common").get("profil_fotograf_guncelle").type_index,
                    "nesne": 'User',
                    "nesne_id": user.id,
                    "ekstra_mesaj": "{} adlı kullanıcı profil fotoğrafını güncelledi.".format(
                        user.username)
                }
                signal_sender(**signal_payload)
                flash(_("Avatariniz guncellendi."))
            else:
                flash(_("Avatarınızı güncellemek için bir resim seçmelisiniz."))
        except ValueError as vexc:
            flash(str(vexc))

        return redirect(url_for('kullanici_profil.avatar'))

zopsedu/common/kullanici_profil/templates/avatar_guncelle.html
{% extends "profil_base.html" %}
{% from "macros/utils/flask_messages/flask_messages.html" import big_flash_message %}
{% block profil %}


    <div class="card">
        <div class="card-content">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12 ">
                        {{ big_flash_message() }}
                        <form class="form" method="post" enctype="multipart/form-data">
                            <div class="form-body">
                                <div class="text-center col-md-12">
                                    {{ avatar_form.csrf_token }}
                                    {{ avatar_form.avatar.label }}
                                    {{ avatar_form.avatar }}
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="text-center col-md-12">
                                    {{ avatar_form.guncelle(class="btn btn-success") }}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

zopsedu/common/kullanici_profil/templates/ozgecmis.html
{% extends "profil_base.html" %}
{% from "macros/utils/flask_messages/flask_messages.html" import big_flash_message %}


{% block profil %}
    <div class="card">
        <div class="card-content">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12 ">
                        {{ big_flash_message() }}
                        <form class="form"
                              action="{{ url_for('kullanici_profil.KullaniciProfilView:ozgecmis_kaydet') }}"
                              method="POST" enctype="multipart/form-data">
                            {{ kayit_formu.csrf_token() }}
                            <div class="form-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <h4 class="form-section"><i class="ft-user"></i> {{ kayit_formu.tecrube.label }}
                                        </h4>
                                        <div class="form-group row">
                                            <div class="col-md-12">
                                                {{ kayit_formu.tecrube }}
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <div class="col-md-6">
                                                <div class="alert alert-warning alert-dismissible mb-2" role="alert">
                                                    <button type="button" class="close" data-dismiss="alert"
                                                            aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                    {{ kayit_formu.ozgecmis_dosya.label }}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <div class="col-md-3">
                                                {{ kayit_formu.ozgecmis_dosya }}
                                            </div>
                                            <div class="col-md-3">
                                                {% if kayit_formu.ozgecmis_dosya_id.data %}
                                                    <a href="{{ url_for("FileView:file_download", file_id=kayit_formu.ozgecmis_dosya_id.data) }}">
                                                        <button class="btn btn-info" type="button">
                                                            {{ _('Özgeçmiş İndir') }}
                                                        </button>
                                                    </a>
                                                {% endif %}
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="text-center col-md-12">
                                    {{ kayit_formu.kaydet(class="btn btn-success") }}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

zopsedu/common/kullanici_profil/templates/parola.html
{% extends "profil_base.html" %}
{% from "macros/utils/flask_messages/flask_messages.html" import big_flash_message %}
{% from "macros/form_helpers/error_fields.html" import error %}

{% block profil %}
    <div class="card">
        <div class="card-content">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12 ">
                        {{ big_flash_message() }}
                        <form class="form" method="post">
                            {{ parola_form.csrf_token }}
                            <div class="form-body">
                                <div class="form-group row">
                                    <div class="text-center col-md-12">
                                        {{ parola_form.old_password(**{'class':'form-control form-control-lg'}) }}
                                        {{ error(parola_form.old_password ) }}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="text-center col-md-12">
                                        {{ parola_form.new_password(**{'class':'form-control form-control-lg'}) }}
                                         {{ error(parola_form.new_password) }}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="text-center col-md-12">
                                        {{ parola_form.re_password(**{'class':'form-control form-control-lg'}) }}
                                        {{ error(parola_form.re_password) }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="text-center col-md-12">
                                    {{ parola_form.degistir(class='btn btn-success') }}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

zopsedu/common/kullanici_profil/templates/profil.html
{% extends "profil_base.html" %}
{% from 'macros/form_helpers/text_fields.html' import render_text_field %}
{% from 'macros/profil_bilgileri.html' import harici_ogretim_elemani_view, akademik_personel_view,bap_memuru_view %}

{% block profil %}

    <div class="card">
        <div class="card-content">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12 ">
                        {% if personel %}
                            {{ akademik_personel_view(user=user, person = user.person, personel=personel, odeme_bilgileri = user.person.odeme_bilgileri) }}
                        {% endif %}
                        {% if bap_memuru %}
                            {{ bap_memuru_view(user=user, person = user.person, personel=personel, odeme_bilgileri = user.person.odeme_bilgileri) }}
                        {% endif %}
                        {% if harici_ogretim_elemani %}
                            {{ harici_ogretim_elemani_view(form=form, args=args) }}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

zopsedu/common/kullanici_profil/templates/profil_base.html
{% extends "base.html" %}

{% block context %}
    <div class="content-header row">
    </div>

    <div class="content-body">
        <div id="user-profile">
            <div class="row">
                <div class="col-12">
                    <div class="card profile-with-cover">
                        <div class="card-img-top img-fluid bg-cover height-300"
                             style="background: url({{ url_for('static', filename = 'assets/img/login-bg-10.jpg') }}) 50%;"></div>
                        <div class="media profil-cover-details w-100">
                            <div class="media-left pl-2 pt-2">
                                <a href="#" class="profile-image">
                                    <img src="{{ avatar_url | default(url_for('static', filename = 'assets/img/user-13.jpg'), true) }}"
                                         class="rounded-circle img-border height-100" alt="Card image">
                                </a>
                            </div>
                            <div class="media-body pt-3 px-2">
                                <div class="row">
                                    <div class="col">
                                        <h3 class="card-title">{{ session['user_ad_soyad'] }}</h3>
                                    </div>
                                    <div class="col text-right">
                                        <a href="{{ url_for('kullanici_profil.avatar') }}">
                                            <button type="button" class="btn btn-success">
                                                {{ _('Avatarı Güncelle') }}
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <nav class="navbar navbar-light navbar-profile align-self-end">
                            <button class="navbar-toggler d-sm-none" type="button" data-toggle="collapse"
                                    aria-expanded="false" aria-label="Toggle navigation"></button>
                            <nav class="navbar navbar-expand-lg">
                                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                    <ul class="navbar-nav mr-auto">

                                        <li class="nav-item active">
                                            <a class="nav-link"
                                               href="{{ url_for('kullanici_profil.profil_goruntule') }}">
                                                {{ _('Profili Görüntüle') }}
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{{ url_for('mesaj.MesajView:gelen_kutusu') }}">
                                                {{ _('Gelen Kutusu') }}</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link"
                                               href="{{ url_for('kullanici_profil.KullaniciProfilView:ozgecmis_goruntule') }}">
                                               {{ _('Özgeçmişi Görüntüle') }}</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{{ url_for('kullanici_profil.rol_degistir') }}">
                                                 {{ _('Rol Değiştir') }} </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link"
                                               href="{{ url_for('kullanici_profil.parola_degistir') }}">
                                                {{ _('Parola Değiştir') }} </a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </nav>
                    </div>
                </div>
            </div>
            <section>
                {% block profil %}
                {% endblock %}
            </section>
        </div>
    </div>


{% endblock %}