zopsedu/bap/hakem/forms.py
"""Hakem Kayit ve Arama Formlari"""

from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, validators, BooleanField
from flask_babel import gettext as _
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Email, Length

from zopsedu.models.helpers import BirimTipiEnum
from zopsedu.personel.models.hakem import HakemTuru
from zopsedu.lib.form.fields import Select2Field

HAKEM = [(tur.name, tur.value) for tur in HakemTuru]


class HakemSearchForm(FlaskForm):
    """Proje Arama Formu"""
    ad = StringField(label=_('Adı'), validators=[Length(max=50)])
    soyad = StringField(label=_('Soyadı'), validators=[Length(max=50)])
    bolum = Select2Field(label=_('Bölüm'), url='/select/bolum')
    kurum_ici_option = SelectField(label='Kurum İçi',
                                   choices=[('0', 'Hepsi'), ('1', 'Kurum İçi'),
                                            ('2', 'Kurum Dışı')], default=0)

    choice = HakemTuru.choices()
    choice = [('0', 'Hepsi')] + choice

    hakem_turu_option = SelectField(label='Hakem Türü', choices=choice, default=0)

    def validate(self):
        if not any([self.ad.data,
                    self.soyad.data]):
            return False
        return True


class KurumIciHakemKayitForm(FlaskForm):
    """Proje Kayit Formu"""
    personel_sec = Select2Field(label=_('Adı Soyadı'), validators=[
        validators.DataRequired(message=_('Bu alan boş bırakılamaz.'))], url='/select/personel')

    kurum_ici_hakem_turu = SelectField(label=_('Hakem Türü'),
                                       choices=HAKEM)


class KurumDisiHakemKayitForm(FlaskForm):
    """Proje Kayit Formu"""

    ad = StringField(label=_('Adı'), validators=[Length(max=50)])
    soyad = StringField(label=_('Soyadı'), validators=[Length(max=50)])
    universitede_gorev_almayan = BooleanField(
        label=_('Herhangi bir üniversitede görev almayan hakem ekle'),
        default=False)

    kurum = StringField(label='Kurum', validators=[Length(max=120)])
    daire = StringField(label='Daire', validators=[Length(max=120)])
    birim = StringField(label='Birim', validators=[Length(max=120)])

    universite = Select2Field(_('Üniversite Seç'),
                              url="/select/birim",
                              placeholder=_("Üniversite"),
                              node_name="fakulte_parent",
                              birim_tipi=BirimTipiEnum.universite.value,
                              kurum_ici=False)

    fakulte = Select2Field(_('Fakülte Seç'), url="/select/birim",
                           placeholder=_("Fakülte"),
                           dependent="fakulte_parent",
                           node_name="bolum_parent",
                           birim_tipi=BirimTipiEnum.fakulte.value,
                           kurum_ici=False)

    bolum = Select2Field(_('Bölüm Seç'),
                         url="/select/birim",
                         placeholder=_("Bölüm"),
                         dependent="bolum_parent",
                         birim_tipi=BirimTipiEnum.bolum.value,
                         kurum_ici=False)

    unvan = Select2Field(label=_('Ünvan'),
                         validators=[
                             DataRequired(
                                 message=_("Ünvan boş bırakılamaz"))
                         ],
                         url='/select/hitap_unvan')

    email = EmailField('E-posta',
                       validators=[DataRequired(message=_('E-posta alanı boş bırakılamaz')),
                                   Email(message='Bir email adresi girmelisiniz'), Length(max=80)])

    hakem_turu = SelectField(label=_('Hakem Türü'),
                             choices=HAKEM)

zopsedu/bap/hakem/blueprint.py
"""HAKEM KAYIT VE ARAMA MODULÜ"""
from flask import Blueprint
from flask_menu.classy import register_flaskview
from zopsedu.bap.hakem.views import HakemView

# pylint: disable=invalid-name
hakem_bp = Blueprint(
    "hakem",
    __name__,
    template_folder='templates/'
)

HakemView.register(hakem_bp, route_base="/hakem")
register_flaskview(hakem_bp, HakemView)

# pylint: enable=invalid-name

zopsedu/bap/hakem/views.py
import random
import string

from flask import render_template, request, jsonify, url_for, render_template_string
from flask_classful import FlaskView, route
from flask_login import login_required, current_user
from flask_babel import gettext as _
from sqlalchemy import desc
from sqlalchemy.orm import lazyload
from werkzeug.datastructures import ImmutableMultiDict

from zopsedu.auth.models.auth import User
from zopsedu.auth.permissions import permission_dict
from zopsedu.bap.models.proje import Proje
from zopsedu.bap.models.proje_detay import ProjeHakemleri
from zopsedu.lib.db import DB
from zopsedu.lib.error_logger import CustomErrorHandler
from zopsedu.lib.signals.signal_sender import signal_sender
from zopsedu.lib.user_activity_messages import USER_ACTIVITY_MESSAGES
from zopsedu.models import Hakem, Person
from zopsedu.auth.lib import auth, Permission
from zopsedu.personel.models.personel import Personel

from .forms import HakemSearchForm, KurumIciHakemKayitForm, KurumDisiHakemKayitForm


def random_pw():
    chars = string.ascii_letters + string.digits
    return "".join([random.choice(chars) for i in range(8)])


class HakemView(FlaskView):
    excluded_methods = [
        "qry"
    ]

    @property
    def qry(self):
        """
        Proje ve ilgili alanlari icin query nesnesi olustur.
        Returns:
        """

        return DB.session.query(Hakem). \
            join(Person, Person.id == Hakem.person_id). \
            add_columns(
            Person.ad.label('ad'),
            Person.soyad.label('soyad'),
        )

    def process_data(self, result, form_data, total_record):
        data = [[
            index + 1,
            r.ad + ' ' + r.soyad,
            r.Hakem.universite.ad if r.Hakem.universite else r.Hakem.kurum if r.Hakem.kurum else '-',
            r.Hakem.fakulte.ad if r.Hakem.fakulte else r.Hakem.daire if r.Hakem.daire else '-',
            r.Hakem.bolum.ad if r.Hakem.bolum else r.Hakem.birim if r.Hakem.birim else '-',
            r.Hakem.hitap_unvan.ad,
            r.Hakem.hakem_turu.value,
            """<a href="{}">
            <span class="float-left  fa ft-search fa-2x"></span>
            </a>""".format(url_for('hakem.hakem_detay', hakem_id=r.Hakem.id)),
            render_template_string(
                """
                {% if kurum_ici_mi %}
                {{ _('Düzenlenemez') }}
                {% else %}
                    <a href="{{url}}">
                    <span class="float-left fa fa-edit fa-2x"></span>
                    </a>
                 {% endif %}   
                    """, url=url_for('hakem.hakem_duzenle', hakem_id=r.Hakem.id),
                kurum_ici_mi=r.Hakem.kurum_ici)
        ] for index, r in enumerate(result)]

        return jsonify({"data": data,
                        "draw": form_data['draw'],
                        "recordsFiltered": total_record,
                        "recordsTotal": total_record})

    @login_required
    @auth.requires(Permission(*permission_dict["bap"]["hakem"]["hakem_listemele"]),
                   menu_registry={"path": ".bap.proje.hakem", "title": _("Hakem Arama"),
                                  "order": 4})
    @route('/hakem-arama', methods=["GET"])
    def hakem_listele(self):
        """Hakem Arama Ekrani"""

        hakem_arama_form = HakemSearchForm()

        return render_template('arama.html', form=hakem_arama_form)

    @login_required
    @route('/hakem-kayit', methods=['GET'], endpoint='hakem_kayit')
    @auth.requires(Permission(*permission_dict["bap"]["hakem"]["hakem_kayit_ekleme"]))
    def hakem_kayit(self):
        """Hakem Kayit ekrani"""

        kurum_ici_hakem_form = KurumIciHakemKayitForm()
        kurum_disi_hakem_form = KurumDisiHakemKayitForm()

        return render_template('kayit.html', kurum_ici_hakem_form=kurum_ici_hakem_form,
                               kurum_disi_hakem_form=kurum_disi_hakem_form)

    @login_required
    @route('/hakem-kayit-kurum-ici', methods=['POST'], endpoint='hakem_kayit_kurum_ici')
    @auth.requires(Permission(*permission_dict["bap"]["hakem"]["hakem_kayit_ekleme"]))
    def hakem_kayit_kurum_ici(self):
        """Kurum içi hakem kayıt için post methodunu karşılayan view"""

        form = request.get_json()['kurum_ici']
        imd = ImmutableMultiDict([(element['name'], element['value']) for element in form])
        kurum_ici_form = KurumIciHakemKayitForm(imd)

        if kurum_ici_form.validate():
            personel_id = kurum_ici_form.personel_sec.data

            hakem_kayitli_mi = DB.session.query(Hakem).filter_by(personel_id=personel_id).first()

            if not hakem_kayitli_mi:

                hakem = Hakem()
                personel = DB.session.query(Personel).filter_by(id=personel_id).first()
                hakem.unvan = personel.unvan
                hakem.universite_id = personel.birim
                hakem.fakulte_id = personel.birim
                hakem.personel_id = personel_id
                hakem.person_id = personel.person_id
                hakem.bolum_id = personel.birim
                hakem.hakem_turu = kurum_ici_form.kurum_ici_hakem_turu.data
                hakem.kurum_ici = True
                try:
                    DB.session.add(hakem)
                    DB.session.commit()
                except Exception as exc:
                    DB.session.rollback()
                    CustomErrorHandler.error_handler(hata="Kurum içi hakem eklenirken bir hata "
                                                          "oluştu." "Hata: {}".format(exc))

                    return jsonify(status="error"), 500

                signal_payload = {
                    "message_type": USER_ACTIVITY_MESSAGES.get("bap").get(
                        "personel_hakem_yap").type_index,
                    "nesne": 'Hakem',
                    "nesne_id": hakem.id,
                    "etkilenen_nesne": "Personel",
                    "etkilenen_nesne_id": personel.id,
                    "ekstra_mesaj": "{} adlı kullanıcı, {} {} adlı personeli hakem olarak ekledi ".format(
                        current_user.username,
                        personel.person.ad,
                        personel.person.soyad)
                }
                signal_sender(**signal_payload)

                return jsonify(status="success")

            return jsonify(status="error", error_message="Personel hakem olarak kayıtlı.!"), 500

        return jsonify(status="error", error_message="Lütfen formu eksiksiz doldurunuz.!"), 400

    @login_required
    @route('/hakem-kayit-kurum-disi', methods=['POST'], endpoint='hakem_kayit_kurum_disi')
    @auth.requires(Permission(*permission_dict["bap"]["hakem"]["hakem_kayit_ekleme"]))
    def hakem_kayit_kurum_disi(self):
        """Kurum dışı hakem kayıt için post methodunu karşılayan view"""

        form = request.get_json()['kurum_disi']
        imd = ImmutableMultiDict([(element['name'], element['value']) for element in form])
        kurum_disi_form = KurumDisiHakemKayitForm(imd)

        if kurum_disi_form.validate():
            try:
                harici_hakem_ekli_mi = DB.session.query(Person).filter(
                    Person.birincil_eposta == kurum_disi_form.email.data).first()

                if harici_hakem_ekli_mi:
                    return jsonify(status="error",
                                   error_message="İlgili eposta adresi başka bir kişi tarafından "
                                                 "kullanılmaktadır. Lütfen başka bir eposta "
                                                 "adresiyle tekrar deneyiniz!"), 500

                user = User()
                user.username = kurum_disi_form.email.data
                user.password = random_pw()
                user.email = kurum_disi_form.email.data
                DB.session.add(user)
                DB.session.flush()

                person = Person()
                person.ad = kurum_disi_form.ad.data
                person.soyad = kurum_disi_form.soyad.data
                person.birincil_eposta = kurum_disi_form.email.data
                person.user_id = user.id
                DB.session.add(person)
                DB.session.flush()

                hakem = Hakem()
                hakem.unvan = kurum_disi_form.unvan.data
                if kurum_disi_form.universitede_gorev_almayan.data:
                    hakem.kurum = kurum_disi_form.kurum.data
                    hakem.daire = kurum_disi_form.daire.data
                    hakem.birim = kurum_disi_form.birim.data
                else:
                    hakem.universite_id = kurum_disi_form.universite.data
                    hakem.fakulte_id = kurum_disi_form.fakulte.data
                    hakem.bolum_id = kurum_disi_form.bolum.data

                hakem.hakem_turu = kurum_disi_form.hakem_turu.data
                hakem.person_id = person.id
                hakem.kurum_ici = False

                DB.session.add(hakem)
                DB.session.commit()
            except Exception as exc:
                DB.session.rollback()
                CustomErrorHandler.error_handler(hata="Kurum dışı hakem eklenirken bir hata oluştu."
                                                      "Hata: {}".format(exc))
                return jsonify(status="error"), 500

            signal_payload = {
                "message_type": USER_ACTIVITY_MESSAGES.get("bap").get(
                    "person_hakem_yap").type_index,
                "nesne": 'Hakem',
                "nesne_id": hakem.id,
                "etkilenen_nesne": "Person",
                "etkilenen_nesne_id": person.id,
                "ekstra_mesaj": "{} adlı kullanıcı, {} {} adlı kurum dışı hakem olarak ekledi ".format(
                    current_user.username,
                    person.ad,
                    person.soyad)
            }
            signal_sender(**signal_payload)

            return jsonify(status="success")

zopsedu/yonetim/bap_yonetimi/views/hakem.py
from flask import current_app, render_template, request, redirect, url_for, flash
from flask_babel import gettext as _
from flask_classful import FlaskView, route
from flask_login import login_required, current_user

from zopsedu.auth.lib import auth, Permission
from zopsedu.auth.permissions import permission_dict
from zopsedu.lib.sessions import SessionHandler
from zopsedu.yonetim.bap_yonetimi.common import genel_ayarlar_guncelle
from zopsedu.lib.db import DB
from zopsedu.lib.signals.signal_sender import signal_sender
from zopsedu.lib.user_activity_messages import USER_ACTIVITY_MESSAGES
from zopsedu.models import GenelAyarlar
from zopsedu.yonetim.bap_yonetimi.forms.hakem import HakemForm


class HakemAyarlarView(FlaskView):

    @staticmethod
    @login_required
    @auth.requires(Permission(*permission_dict["yonetim"]["bap_yonetimi"]["hakem_ayarlari"]),
                   menu_registry={'path': '.yonetim.bap.hakem_ayarlari',
                                  'title': _("Hakem"), 'order': 10})
    @route('/hakem', methods=['GET'])
    def get():
        """Ayarlar ekraninin goruntulendigi view"""
        universite_id = SessionHandler.universite_id()
        genel_ayar = DB.session.query(GenelAyarlar).filter_by(universite_id=universite_id,
                                                              aktif_mi=True).first()

        if genel_ayar and genel_ayar.bap_hakem:
            form = HakemForm(**genel_ayar.bap_hakem)
        else:
            form = HakemForm()

        return render_template("hakem.html", form=form)

    @staticmethod
    @login_required
    @auth.requires(Permission(*permission_dict["yonetim"]["bap_yonetimi"]["hakem_ayarlari"]))
    @route('/hakem', methods=['POST'])
    def post():
        """
        Ayarlarin kaydedildiği view

        """

        form = HakemForm(request.form)
        if form.validate():
            form_data = dict(form.data)
            form_data.pop('csrf_token')
            universite_id = SessionHandler.universite_id()
            genel_ayar = DB.session.query(GenelAyarlar).filter_by(
                universite_id=universite_id,
                aktif_mi=True).first()
            if genel_ayar:
                yeni_ayarlar = genel_ayarlar_guncelle(genel_ayar, "bap_hakem", form_data)
            else:
                yeni_ayarlar = GenelAyarlar(universite_id=universite_id, bap_hakem=form_data)

            DB.session.add(yeni_ayarlar)
            DB.session.commit()
            flash(_("Ayarlarınız başarılı bir şekilde kayıt edildi."))
            signal_payload = {
                "message_type": USER_ACTIVITY_MESSAGES.get("ayarlar").get(
                    "bap_hakem_guncelle").type_index,
                "nesne": 'GenelAyarlar',
                "nesne_id": yeni_ayarlar.id,
                "ekstra_mesaj": "{} adlı kullanıcı, bap hakem ayarlarını güncelledi.".format(
                    current_user.username)
            }
            signal_sender(**signal_payload)
            return redirect(url_for('bap_yonetimi.HakemAyarlarView:get'))

        return render_template("hakem.html", form=form)

zopsedu/bap/hakem/templates/arama.html
{% extends "base.html" %}


{% block context %}

    <div class="content-header row">
        <div class="content-header-left col-md-8 col-12 mb-2">
            <h3 class="content-header-title mb-0 d-inline-block">  {{ _("Hakem Arama") }} </h3>
        </div>
    </div>
    <div class="content-body">
        <section id="hakem-arama-alani">
            <div class="card">
                <div class="card-content collapse show">
                    <div class="card-body card-dashboard">
                        <div id="aramaAlani">
                            {% if form %}
                                <form class="form" id="detayli-arama-form">
                                    <div class="form-body">
                                        <div class="row">
                                            <div class="col-md-12">
                                                {{ form.csrf_token }}
                                                <div class="form-group row">
                                                    <div class="col-md-3">
                                                        {{ form.ad.label }}
                                                    </div>
                                                    <div class="col-md-3">
                                                        {{ form.ad(class="form-control") }}
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <div class="col-md-3">
                                                        {{ form.soyad.label }}
                                                    </div>

                                                    <div class="col-md-3">
                                                        {{ form.soyad(class="form-control") }}
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <div class="col-md-3">
                                                        {{ form.hakem_turu_option.label }}
                                                    </div>
                                                    <div class="col-md-3">
                                                        {{ form.hakem_turu_option(class="form-control") }}
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <div class="col-md-3">
                                                        {{ form.kurum_ici_option.label }}
                                                    </div>
                                                    <div class="col-md-3">
                                                        {{ form.kurum_ici_option(class="form-control") }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                                <div>
                                    <button id="ara" class="btn btn-search btn-success m-r">Ara</button>
                                    <button id="temizle" class="btn btn-clear btn-warning">Temizle</button>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section id="hakem-listesi">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">{{ _('Hakem Listesi') }}</h4>
                    <div class="btn-group float-md-right">
                        <a href="{{ url_for('hakem.hakem_kayit') }}">
                            <button class="btn btn-success">{{ _('Hakem Ekle') }}</button>
                        </a>
                    </div>
                </div>
                <div class="card-content collapse show">
                    <div class="card-body card-dashboard">
                        <div class="row">
                            <div class="col-md-12">
                                <table id="data-table"
                                       class="table table-striped table-bordered dataex-visibility-selector dataTable"
                                       role="grid" style="width: 100%;">
                                    <thead>
                                    <tr role="row">
                                        <th style="width:5%;">{{ _('#') }}</th>
                                        <th style="width:20%;">{{ _('Ad Soyad') }}</th>
                                        <th style="width:15%;">{{ _('Kurum / Üniversite') }}</th>
                                        <th style="width:15%;">{{ _('Daire / Fakülte') }}</th>
                                        <th style="width:15%;">{{ _('Birim / Bölüm') }}</th>
                                        <th style="width:15%;">{{ _('Ünvan') }}</th>
                                        <th style="width:10%;">{{ _('Hakem Türü') }}</th>
                                        <th class="all" style="width:5%;">{{ _('Hakem Detay') }}</th>
                                        <th class="all" style="width:5%;">{{ _('Hakem Düzenle') }}</th>
                                    </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
        </section>
    </div>
    <!-- ================== BEGIN PAGE LEVEL JS ================== -->
    {% from 'macros/utils/dataTables/custom_serverside.html' import custom_serverside_table %}
    {{ custom_serverside_table(endpoint=url_for('hakem.hakem_search'), id="data-table",ara_button_id="#ara",temizle_button_id="#temizle",search_form_id='#detayli-arama-form') }}
    <!-- ================== END PAGE LEVEL JS ================== -->
{% endblock %}

zopsedu/bap/hakem/templates/edit.html
{% extends "base.html" %}
{% from 'macros/kaydet.html' import kurum_disi_hakem %}
{% block context %}

    <div class="content-header row">
        <div class="content-header-left col-md-8 col-12 mb-2 breadcrumb-new">
            <h3 class="content-header-title mb-0 d-inline-block"> {{ _("Hakem Düzenleme") }}</h3>
        </div>
        <div class="content-header-right col-md-4 col-12">
            <div class="btn-group float-md-right">
                <a href="{{ url_for('hakem.HakemView:hakem_listele') }}">
                    <button class="btn btn-success">
                        {{ _("Hakem Arama Sayfasina Git") }}
                    </button>
                </a>
            </div>
        </div>
    </div>
    <div class="content-body">
        <section id="hakem-duzenleme" class="card">
            <div class="card-content">
                <div class="card-body">
                    {{ kurum_disi_hakem(kurum_disi_hakem_form, url=url_for('hakem.hakem_duzenle_post',hakem_id=hakem)) }}
                </div>
            </div>
        </section>
    </div>

{% endblock %}

zopsedu/bap/hakem/templates/kayit.html
{% extends "base.html" %}
{% from 'macros/kaydet.html' import kurum_ici_hakem, kurum_disi_hakem %}
{% block context %}
    <div class="content-header row">
        <div class="content-header-left col-md-8 col-12 mb-2 breadcrumb-new">
            <h3 class="content-header-title mb-0 d-inline-block"> {{ _("Hakem Kayıt") }}</h3>
        </div>
        <div class="content-header-right col-md-4 col-12">
            <div class="btn-group float-md-right">
                <a href="{{ url_for('hakem.HakemView:hakem_listele') }}">
                    <button class="btn btn-success">
                        {{ _("Hakem Arama Sayfasina Git") }}
                    </button>
                </a>
            </div>
        </div>
    </div>
    <div class="content-body">
        <section id="hakem-kayit-tab" class="card">
            <div class="card-content">
                <div class="card-body">
                    <ul class="nav nav-tabs nav-justified">
                        <li class="nav-item">
                            <a class="nav-link active show" id="active-tab" data-toggle="tab" href="#kurum-ici-tab"
                               aria-controls="active"
                               aria-expanded="true">{{ _("Kurum İçi") }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="link-tab" data-toggle="tab"
                               href="#kurum-disi-tab"
                               aria-controls="link"
                               aria-expanded="false">{{ _("Kurum Dışı") }}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </section>
        <section id="hakem-kayit-tab-content" class="card">
            <div class="card-content">
                <div class="card-body">
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active show" id="kurum-ici-tab"
                             aria-labelledby="base-kurum-ici">
                            {{ kurum_ici_hakem(kurum_ici_hakem_form,url=url_for('hakem.hakem_kayit_kurum_ici')) }}
                        </div>
                        <div class="tab-pane" id="kurum-disi-tab"
                             aria-labelledby="base-kurum-disi">
                            {{ kurum_disi_hakem(kurum_disi_hakem_form,url=url_for('hakem.hakem_kayit_kurum_disi'))}}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}